version: 1

formatters:
  detailed:
    format: '[%(asctime)s] %(levelname)s - %(message)s (%(filename)s:%(lineno)d - %(funcName)s)'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/app.log
    maxBytes: 1048576  # 1MB
    backupCount: 5

loggers:
  app_logger:
    level: DEBUG
    handlers: [console, file]
